### ISSUE TITLE
Why feature folder exists ?

### ISSUE THREAD

**Issue by floross** [JimmyBeldone/reapt#4]
Why the `feature` folder exist and it is not inside the `views` folder ?

**Comment by JimmyBeldone** [comment]
In future versions you'll be able to choose with CLI if you need some features or not installing this starterkit, each folder in ```features/``` will have its own repo.

For now I need these features in every projects I work on but I plan to move it.

I could have moved ```features/``` in ```views/components/default/```, but features come with their own reducers, actions, container / presentational components and editable config file, where default components does not.  

If you have ideas about structures I'm all ears ^^
